name: DB Migration

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Enter the starting number"
        required: true
        default: "1"
      max_retries:
        description: "Enter the max retries"
        required: true
        default: "3"
      retry_delay:
        description: "Enter the retry delay"
        required: true
        default: "3"

jobs:
  db-migration:
    environment: cloudflare

    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Clone SQL repository
      - name: Clone SQL Repository
        run: git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/dbchord/db-sql.git

      # Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run npm script
      - name: Run Script
        run: |
          set +e  # Disable exit on error
          idx=0
          start=${{ github.event.inputs.start }}
          max_retries=${{ github.event.inputs.max_retries }}
          retry_delay=${{ github.event.inputs.retry_delay }}

          for file in ./db-sql/*; do
            if [[ -f "$file" && $idx -gt $start ]]; then
              attempt=0
              success=false

              while [[ $attempt -lt $max_retries ]]; do
                echo "[$((idx+1))] ($((attempt+1))/$((max_retries))): $file"
                echo | npm start -- --file=$file

                # Check if the command was successful
                if [[ $? -eq 0 ]]; then
                  success=true
                  break
                else
                  curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" -d "chat_id=$TELEGRAM_CHAT_ID" -d "text=Failed to migrate!\nIndex: $idx\nFile: $file"
                  echo "Error processing file: $file. Retrying in $retry_delay seconds..."
                  sleep $retry_delay
                fi

                attempt=$((attempt + 1))
              done

              if [[ $success == false ]]; then
                echo "Failed to process file after $max_retries attempts: $file"
                continue
              fi
            fi

            idx=$((idx + 1))
          done
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

      # Upload Wrangler Logs
      - name: Upload Wrangler Logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: wrangler-logs
          path: /home/runner/.config/.wrangler/logs/
