name: DB Migration

on:
  workflow_dispatch:
    inputs:
      start:
        description: "Enter the starting number"
        required: true
        default: "1"

jobs:
  db-migration:
    environment: cloudflare

    runs-on: ubuntu-latest

    steps:
      # Checkout the current repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Clone SQL repository
      - name: Clone SQL Repository
        run: git clone https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/dbchord/db-sql.git

      # Set up Node.js
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Install dependencies
      - name: Install Dependencies
        run: npm ci

      # Run npm script
      - name: Run Script
        run: |
          start=${{ github.event.inputs.start }}
          counter=0
          for file in ./dbchord-sql/*; do
            if [[ -f "$file" && $counter -gt $start ]]; then
              echo "[$((counter+1))]: $file"
              echo | npm start -- --file=$file
            fi
            counter=$((counter+1))
          done
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
